
### Create a new major
POST http://localhost:8080/api/v1/majors
Content-Type: application/json

{
  "name": "Quản trị kinh doanh"
}

### Find all majors
GET localhost:8080/api/v1/majors
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtaW5oQGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzM0ODA2MzQ0LCJleHAiOjE3MzQ4MDcyNDR9.ZO96TCfTh0wd_BNg1mke6SNtFhA9o7PAVBXdr-f6ASTCprFACwponhf1zq4HknQJG0ZGT_RsbgM9bVMkecOZ1g

### Update major
PUT http://localhost:8080/api/v1/majors/2
Content-Type: application/json

{
  "name": "Công nghệ thông tin",
  "majorId": 1
}

### Delete a major by major id
DELETE localhost:8080/api/v1/majors/2

### Seach major by name (Not works currently)
GET localhost:8080/api/v1/majors/cong